# PyTorch AutoGrad

In [19]:
import torch

In [20]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]]).requires_grad_(True)

requires_grad는 autograd 에 모든 연산(operation)들을 추적함

In [23]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [22]:
y.backward()

$$\begin{gathered}
x=\begin{bmatrix}
x_{(1,1)} & x_{(1,2)} \\
x_{(2,1)} & x_{(2,2)}
\end{bmatrix}\\
\\
x_1=x+2 \\
x_2=x-2 \\
\\
\begin{aligned}
x_3&=x_1\times{x_2} \\
&=(x+2)(x-2) \\
&=x^2-4
\end{aligned} \\
\\
\begin{aligned}
y&=\text{sum}(x_3) \\
&=x_{3,(1,1)}+x_{3,(1,2)}+x_{3,(2,1)}+x_{3,(2,2)}
\end{aligned} \\
\\
\text{x.grad}=\begin{bmatrix}
\frac{\partial{y}}{\partial{x_{(1,1)}}} & \frac{\partial{y}}{\partial{x_{(1,2)}}} \\
\frac{\partial{y}}{\partial{x_{(2,1)}}} & \frac{\partial{y}}{\partial{x_{(2,2)}}}
\end{bmatrix} \\
\\
\frac{dy}{dx}=2x
\end{gathered}$$

In [5]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


x의 대한 미분 값이 나옴

In [6]:
print(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [7]:
x3.numpy()

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [24]:
x3.detach_().numpy()

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)

detach를 통해 requires_grad를 중지할 수 있음

# y가 벡터인 경우

In [13]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)


In [14]:
y = 3*a**3 - b**2

In [15]:
external_grad = torch.tensor([1., 1.])
y.backward(gradient=external_grad)

## 방법 2가지
1. 명시적으로 y의 gradient 인자를 전달해야함   
2. y.sum().backward()로 스칼라로 변환한 뒤 backward를 호출 할 수도 있음

In [16]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [18]:
b

tensor([6., 4.], requires_grad=True)